const texts = [
	{
		title: "If I See You in Forty Years",
		text: [
			'“If you told me I should love myself, I would look at you, whoever you’ve become, and declare my undying love for you. But that would be rather worthless, wouldn’t it,” said the professor as he turned to his class. He removed his glasses, wiping them as he went on to explain “So here is our character’s statement.”',
			'He fixed the glasses on his nose and peered above the heads of his students. “As you well know by now, I’m an unorthodox teacher. I had one rather eclectic. Student,” he said softly, looking away and remembering, searching the recesses of his mind for where that former student was lurking. He found her, peering back at him with a half-smile and bowed head. “Prolific indeed. She left me all her writings, full works, little dabbles, lines like these. I have never once repeated a class. You will continue to finish or elaborate on her writings. Like this one.” He turned and gestured at the words projected behind him, yet his gaze only grazed them at the edges of his vision. “Your assignment is to craft a story around these words. Whether you interpret them literal.” He surveyed his students. “Or use them literal.”',
			'In the back of his head, he stared down the length of his nose at them all, not seeing even one of them that could match that prolific writer he saw in his memory with her half-smile and daunting eyes. “It’s up to you. Three thousand words on my desk when class starts. Dismissed.” He turned his back to the auditorium, pulling off his glasses and cleaning them as he listened to his students chatter, stand and rummage about, and the shuffling of their steps as they climbed to the second floor exits or scuffled, hurrying down and out the first floor door. Resetting his glasses on his nose, he strode back to the desk in front and slipped the folder of submitted papers into his bag.',
			'“Professor,” a student called. It sounded like a lithe female. He hardly looked up as he called back, prompting her to continue. “Sir.” He looked up with a sigh, avoiding her, answering again and this time, tried to put a name to the voice so as to emphasize his impatience but he could hardly remember any of the students, even if it wasn’t the first day, and looked at her.',
			'He held his breath and blinked. She was speaking and he wasn’t listening. With a shake of his head, looking down at his shoes as he removed his glasses, he asked her if she would repeat herself. He was distracted, he said.',
			'“Of course, sir. I was saying. If you don’t mind, could I do more than one version?”',
			'A deep frown drew his face together as he wondered, “Version? How many versions do you figure you could write?”',
			'She shrugged, though he only caught a trace of the movement at his peripheral. “I figured. You said to interpret literal or to use literal. That’s at least two ways I could take it. Right?”',
			'With his glasses back on, he stole a glance at her and stared. “How long,” he muttered.',
			'“Yes, sir?”',
			'He could hardly catch his breath. The sight of her was vexing. “Were you,” he wondered and gestured where she stood, “sitting here the whole time?”',
			'She glanced away. “No, sir,” she admitted softly, “I came in just for the assignment. I’m sorry.”',
			'He blinked, feeling like a cold sweat might start. “At the door,” he replied gruffly as if straining to force out the words, “You were standing there?”',
			'She looked where he gestured and turned back, nodding. “Yes, sir.”',
			'He looked down and away with a shake of his head, trying to backtrack through his thoughts and see if he had seen her or if that had been a memory. Nodding to himself, he admitted his own defeat, rubbing at his face. He cocked his head to the young woman, unable to look at her, and said, “Let it be up to you. If you write more than one, mark the one you want graded. I can comment on the rest.” He stole a glance at her, spying the huge grin that spread across her face.',
			'“Alright,” she answered, “I’ll do that. Thank you, sir.”',
			'“Stop that,” he said, waving his hand at her, a tremble in his fingers, “Don’t. Calling me sir.”',
			'She looked down with a nod. “Yes, professor.”',
			'“And that,” he frowned, “Mister Morrisome will do.”',
			'She stared at him, which he could not stomach. He kept his head cocked, viewing her in his peripheral and resisted the urge to clean his glasses again. “Yes, Mister Morrisome.”',
			'He nodded to himself, while thanking her and waving her away. Shuffling around the table, he made his way to the nearest exit, yet as he moved, he could not help feeling as if she were watching him go. Though he could not see her, he could imagine the eyes of that clear, distinct gaze fixated on him. He adjusted the lapels of his jacket, pulling the ends tighter around himself. It wasn’t cold in the building but with the students milling through the hall, lingering by the squares or lounging out on the grass of the quad, he burrowed into his jacket as if it might shield him from all the noise and movements they made.',
			'He came out a side entrance of the building, where few students strayed, and made his way along the brick walkways to a building nestled at the back of the quad. It was one of the older buildings with a weathered brick facade and stained windows. The classrooms in the building were smaller. They had stacked tables and chairs with blackboards in the front and podiums, rather than desks, for the instructors.',
			'He climbed the steps, two flights that left him winded every day, no matter how many times he went up and down, and navigated around the tree overgrown beside the side entrance. He climbed the last few steps to the door, pulled it open only so much as to slip in, hoping the hem of his jacket didn’t get caught. Once inside, he stopped to catch his breath.',
			'When he looked up, it was the student, or the young woman from his memory, he couldn’t tell but she was standing in front of him, regarding him with a slight smirk and knowing eyes. “You’re getting old,” she said softly, “Don’t you wish you had joined me. Mister Morrisome.”',
			'He huffed. “Now don’t make that a thing,” he chastised and walked right through her. She trailed after him, her cold presence tickling the length of his back. He could hear her humming but there was no sound of footsteps other than his own. Reaching his office door, he fished out his key and jiggled it into the lock. With a sniff, he held still a moment, resisting the urge to pull off his glasses and clean them for the umpteenth time. Jiggling the key and twisting, he got the lock to turn and pushed, opening the door to a clean and tidy little office with shelves of books against every wall, save for the space behind his desk, right beneath a small window near the top corner of the adjacent wall.',
			'Shuffling in, he closed the door, laid his bag on the desk, peeled off his jacket and laid it on the chair, and then reached up, pushing the window out to let in some air. He then looked about, surveying if there was any accumulation of dust on the ground. Whether or not there was, with a huff, he pulled a broom out from beside the desk and swept the small space, shifting a tiny pile of particles to the side, then opened the door and swept it out. As he closed the door with a heavy sigh, he shuffled back and returned the broom to the side. He spun the chair back and sat down.',
			'As he looked up, there was the young woman, or the student, sitting on the edge of his desk, one leg crossed over the other, regarding him with that perpetual half-smirk. She tilted her head one way and then the other. “In your own little corner,” she teased, “Why, you’ll be forgotten here some day.”',
			'He removed his glasses, setting them on the desk, wiped his face and stared at her. “Yes,” he whispered, “I wager. Forgotten like you among all these pages and books.”',
			'She nodded, her gaze lingering over the floor. “At least you found me,” she peered sideways at him, “Thank you, Cory.”',
			'He gave her a solemn nod. “You were my favorite teacher.”',
			'She smiled. “I left that to you.”',
			'He scoffed and spun about to the desk. “That wasn’t your choice.” She shrugged but he hardly saw it. He pulled out the folders of papers from his bag, grumbling. Though she reached out to rub his shoulder, what he felt was a cold pressure, not even in the shape of a hand. He focused solely on the cold pressure against his shoulder and reading the papers, when a knock made him jump and curse under his breath. “Who,” he called out and wiped his face, “Who is it?”',
			'“It’s.” The voice was small and feminine.',
			'“Well,” he prompted.',
			'“This is Cassendy.”',
			'He frowned, drawing a blank. Glancing down, he riffled through the papers, looking for a name that started with Cassidy.',
			'“Cassidy,” he called out, “What’s your class?”',
			'“No, sir. I mean, Mister Morrisome. It’s Cassendy.”',
			'He stilled. His chair creaked as he shifted and stared at the door as if he might see through it to the young woman on the other side. “What is it, Cassendy?”',
			'“May I speak with you, sir? M-Mister Morrisome. Sorry.”',
			'He looked at a spot on the door as if he might see her through it and then at the knob. Shifting, he spun back to his desk, calling out, “Come in.” He kept his back to the door as it opened and the young woman looked about. There was nowhere to sit, the office was so small. He looked out over his shoulder, stopped and retracted when he almost pulled a muscle, but then he spun his chair towards her and peered at her. “What do you need, Miss Cassendy?” He found her looking at all the books surrounding them, reading the titles in a state of mute wonder. “Miss Cassendy,” he called but she did not respond. He barked out her name and she flinched.',
			'“Sorry, sir. Sorry. Mister Morrisome.”',
			'He squinted at her. “You’re too polite,” he grumbled and reached over, picking up his glasses. He set them on his nose without thinking, grimaced and pulled them off to clean them. “What do you need?”',
			'He kept his head lowered, purposely trying not to look at her. It felt as if she were watching him, yet he reasoned against that, wondering why she would stand there just out of arm’s reach and watch him as he cleaned and fumbled with his glasses. As he fixed his glasses on his nose and looked at her, what he reasoned against was exactly what she was doing, watching him with a curious, unwavering gaze. “Miss.” He struggled a moment to remember. “Cassendy. What do you need?”',
			'She blinked but did not answer. Her gaze fell. She was motionless. He watched her, puzzled. Unable to discern what reason she had for coming, he sat back with a creak of his chair and stared at her.',
			'“I thought.” He flinched. Her silence and lack of movement had dragged on so long that to hear her voice was a splash of cold water. Focusing on her, he struggled to make out words he realized weren’t being said. When she finally uttered another word, he had to question himself back and forth to discern that it wasn’t in his head again.',
			'“You’re quite the character,” she said, lifting her head, “Mister Morrisome.” He blinked at her, resisting the urge to clean his glasses. Instead he rubbed his hands together, feeling sweat collect along his palms. He gripped one of the arms of his chair and floundered for an answer. “When I thought about it,” she continued and he could feel her drawing closer. He looked up but the young woman from his memory wasn’t there. “Those words were for you.”',
			'She came up beside him, peering down at him and stepping into his line of sight so that he couldn’t look away and when he looked at her, he was lost, unable to discern if she was the student or the young woman from his memory. She tilted her head as she regarded him with a smile. Looking down at the spot on the desk beside him, she turned and jumped up. He could not protest, seeing how easily she assumed the place of the young woman she resembled. Her smile grew as he looked at her, seeing her face as if looking into the light and making out the features of an angel. “I told you,” she said, “One day.”',
			'He felt a gust of wind, hearing a high whistling and rustling of trees and pages, and ducked his head, closing his eyes as papers flew out and around him. Looking up, he looked to the small window far above his desk. Realizing the young woman wasn’t there anymore, he turned about, looking every which way and found the door closed. His papers were all strewn about but the young woman was gone as if she had never been there.',
			'With a shake of his head, he looked at the mess on his floor, and caught a glimpse of a single paper neatly aligned with the edge of his desk, sitting where either the young woman and student had. Sliding the paper off the desk and holding it in his hands, he read “If I See You in Forty Years.” Taking off his glasses and setting them aside, he rubbed his face, gazing at those words warily. He flipped the title page out of the way and read through the paper.',
			'It was the story of a young woman and a young man. She was his tutor and one of the youngest teachers at the college. Though she taught physics, she was a very prolific writer, always requiring a pencil on her ear and a notepad under arm. The young man was not a science major of any kind, so taking her class and struggling through the material was odd. He intrigued her and she intrigued him. She offered him time during her office hours. He asked her to share her writings with him and he would accept. What a funny man, she thought. Learning that he came from the literature department, she asked for him to teach her too. He found that even stranger, to which she called herself the forever student.',
			'But their days were numbered.',
			'She could not tell him but she wondered what days in the future would be like, especially for him. He would never know, she thought, and so she wrote what she could not say.',
			'“Would you tell me that I should love myself,” she wondered.',
			'Imagining him forty years later, she smiled as he scoffed, an older man with the constant urge to clean his glasses and avoid looking anyone in the eyes because she knew looking in people’s eyes reminded him of the one gaze he would never see again, and as that older man, he told her in gruff tones, “Of course. Love yourself, if that would have kept you alive.” With that image in her mind, she could imagine herself smiling and saying, “If you told me I should love myself, I would look at you, whoever you’ve become, and declare my undying love for you. But that would be rather worthless, wouldn’t it?”',
			'As he reached the quotation, he felt a cold presence against his back and heard the murmur of distant words. “Would you tell me that I should love myself?”',
			'He laid the paper down with shaking hands, gripping them together as he turned, the last words of the paper echoing over and over in his head, he found her standing there behind him, the young woman from his memory. She watched him, waiting. “You should,” he muttered, shaking from deep in his gut, watching her gaze soften and a smile spread across her lips. “If that would have kept you alive.”',
			'“Then I’ll always love you, sir” she whispered as she leaned towards him, “Sorry. Mister Morrisome.”',
			'Her cold presence lingered, even as the sight of her faded in but a second. He turned back to the paper and stroked the page with those words on it, the “I’ll always love you, sir.” Feeling a catch in his breath, he bowed his head as he hunched over, covering his face with his hands as he cried, the same way he cried the day he had found her so cold.'
		]
	},
	{
		title: "His Favorite Girl",
		text: [
			'Let me tell you a little story.',
			'There was a teenage boy, a jock, a football player. He was quiet and people thought he was shy, so quite a few girls liked him. The noisiest man on the team would grab him round the shoulders and encourage him to pick a girl. All the girls that collected around the team members noticed his quiet politeness.',
			'At one of many parties, a girl climbed into his lap. He turned his head away and when she tried to turn his head towards her, he grabbed her wrists, pulling her hands off him. The girl was offended. What did he want, she demanded, was she not good enough. Though that’s what he thought, he told her the only girl he wanted was his girlfriend. Where is she, the girl wondered. The way she smiled made him think that she thought she would be better than anyone he pointed out. He stared at her and said his girlfriend did not attend parties. Her smile quirked. Why, the girl wondered, she from another school or something? He continued to stare at her.',
			'Urging her away, he stood and walked out. He weaved through the crowd of students blocking the front door, only to be caught by another member of the team. They told him about drinking games in the back, some stupid stunt some guy did from the second floor, and finally about some drugs being done in one of the bathrooms. He shook his head. Hey, the guy said, What’s wrong? He shrugged the guy’s hands off his shoulders and shook his head. Leaning in closer, he said, I just want to go home. What’s at home, the guy wondered. He smiled to himself. Not home, he corrected, realizing his mistake, What feels like home.',
			'Before the guy could ask him what that meant, he pushed his way through the rest of the crowd, reaching the front door.',
			'Someone was blocking it, pressed against it. He turned the knob and forced the door open, catching the people’s attention. Where you going, one of them asked. He ignored it. Getting the door open just wide enough, he slipped out, scared of the door being slammed shut and hitting his wrist. Even as it didn’t happen, he descended the front steps, rubbing at and turning his wrist, trying to get out the feeling of potentially getting hurt (and being benched).',
			'He did not bother with a car or a ride on the bus. Instead, he walked down the street and through the neighborhoods. When the cold set in, he kept moving, checking the faces of the houses and their lit windows. Catching glimpses of families, he wondered what that was like. Thinking of his parents, the warmth and light felt so distant, but the thought of one girl brought a smile to his face. It would not leave and just at the thought of her, he understood the warmth and light he saw. He knew what it was.',
			'At the mouth to a familiar cul-de-sac, he smiled up to his ears. Jumping on his feet, he ran past the fences and the houses towards the blue light in a second story window. Racing by the driveway, he vaulted the side door and slowed to a stop in the light from a back porch. As he stepped onto the pavement, he removed his jacket and made his way to the door, looking in. He knocked on the glass.',
			'A woman in the kitchen spotted him and smiled. She called out to someone sitting in the dark living room. A figure stood and lumbered over. It was a man so tall that it was awkward. The man opened the door and let him in. He laid his jacket on a chair. After closing the door, the man ruffled his hair. He laughed as he wiped off his shoes.',
			'Where you been, called the woman from the kitchen. He looked at her and shrugged. A party, he said. He looked away, shaking his head. Ah, she said, catching his attention, Missed her, huh?',
			'He fumbled to answer and decided not to, ducking away. She laughed and the man watched him as he left the kitchen, dining and living area. He hurried up the stairs and headed to the door of the room with blue light. Stopping in front of the door, he took a breath. A grin spread across his face and he couldn’t stop it. He knocked.',
			'In the room sounded another knock. He opened the door and laid eyes on the teenage girl at her desk. She looked at him and a smile broke out on her face. She adjusted her glasses, then gestured back at her bed with her head and then refocused on her computer. He closed the door behind him and crossed to her bed. She had her back to him as he plopped down. He looked around her room, the low shelves running along all the walls except where the bed and desk were, the posters of Star Wars, Stevens Universe, Rick and Morty, Meghan Trainer, and Hairspray, the handmade planetary models hanging from the ceiling, and smiled. He took off his shoes and bending low, tossed them towards the shoe pile to the right of the door. He heard a snort and smiled at the girl’s back.',
			'The girl was a big girl. She was nothing like the typical portrayals of ideal or perceived teenagers on TV. In fact, if there was any close representation of her, it was the awkward, heavyset nerd who was teased or humiliated for her weight and interests. At times, he could see the resemblance. When he became part of the football time and began spending time with party-oriented popular people, she became conscious of spending time with him, not that she spent much time with him anyway, though he was not quick to point that out to her.',
			'Back in middle school, she started becoming obsessed and highly involved with new friends and clubs. He brought it up, wondering why she didn’t spend anymore time with him, and she got angry. She would not talk to him for a week. He was so confused and asked a couple girls for advice. The girls thought he was trying to get their attention and one of them seized the opportunity to be closer to him. It was uncomfortable. He left her without even uttering goodbye.',
			'Not to mention, if he were honest, he’d already been consumed by fantasies at that time of his big and bubbly friend. He masturbated to the idea of her weight, her size, her face, and he was scared she would be disgusted. He thought his friends would be disgusted too. Fat girls weren’t exactly the publicly acceptable targets of teenage hormones.',
			'Back in middle school, when he managed to convince a friend and a couple girls to watch Hairspray with him for an evening, his friend was turned on by the cute blond girl. The girls kept talking, wondering what the boys thought, if they would ever sleep with a fat girl. Rather than lie, he kept silent. He knew if he said that he would sleep with a fat girl that it would be interpreted incorrectly.',
			'After the movie ended, he escaped the room by taking the bowl of popcorn, and hid in the kitchen. One of the girls came down when he took too long. She stood too close. He could not even remember what was said hours later, but somehow, it got to her hugging him. He was surprised by how much disgust he actually felt, and felt so happy that he laughed and hugged the girl back. When he pulled back, she leaned up to kiss him but he wasn’t paying attention and her lips touched his jaw. He jerked back and looked at her. She stared back at him, embarrassed. He knew she must have felt humiliated but he could not afford for anyone to have wrong ideas. What are you doing, he asked her. She uttered word vomit and excused herself back to his room. Sliding to the floor in his kitchen, he felt guilt, but then remembering his reaction to her hug, he grinned to himself and laughed with relief. He was so happy, and then devastated, remembering that his best friend was so focused on her new friends and clubs.',
			'With determination and certainty, he approached his friend. She forgave him easily but the situation had not changed. Most of her time was dedicated to her friends and club activities. One afternoon, she stood him up at her house. He was alone with her parents. Back then, they were not that familiar with him and the silence between them was awkward. Her mother, a robust woman, was nice and made light conversation with him about school, his subjects, and what his family was like. Her father, the man so tall that it was awkward, asked him how he met their daughter. They recognized him from her elementary class in sixth grade, but they had no idea when and how the two started spending time together. So he remembered.',
			'Shortly after classes resumed following winter break, after the bell rang announcing the end of the day and children headed out to join their parents, he hid in a bush, hugging his knees and keeping his head down. He waited, not even daring to look out to see if either of his parents was out there. He prayed whichever one it was that they left without him.',
			'When he heard a rustling, he jumped back. He looked around for some place to hide, scared it was one of his parents coming for him, though an adult would have difficulty getting through the bushes and the rustling would be much larger. When a girl popped her head in to his hiding space, he stared at her, aghast. She stared back at him. Don’t, he whispered, Don’t let them know I’m here. The girl said that was okay, so long as he made space for her. He scooted over. She squeezed in and took more than her half of the space. He did not mind it though.',
			'Until she came and sat with him, he had not realized he was lonely. The girl talked on and on. It made him smile. He had nothing to talk about and every time she tried to defer to him, trying to involve him in the conversation, he had nothing. Eventually, she was skeptical and stopped talking. Do you play anything, she wondered. He peered back at her and shook his head. Read, she wondered. He shook his head. What about TV? When he shook his head, she stared at him, frozen with shock.',
			'Having an idea, she got a determined look on her face and then looked out. What do your parents look like, she whispered. He described his parents. She didn’t see them and urged him to come with her. They snuck out of the school and went to her house. She did not take him in though. Instead, she ran in, grabbed something and came back, giving him a DS and a couple games. He was surprised. He took the DS and games, playing them as he strolled back home. When he arrived home, his parents had been so scared by his disappearance that for the first time, he saw them worried, fussing over him. His mom even hugged him. Though his parents were still awkward with affection after that, they were far more careful, which was probably the way they tried to show consideration.',
			'After concluding his story, the parents of his favorite girl were so shocked that for a few moments, they were completely silent. A few days later, her mom would comment on the second DS they had to buy because some brownie got in their house and was stealing things, but at that moment, after he told his story, the only sound was the TV and then the front door as his favorite girl in the world entered. The moment she saw him, an array of emotions played across her face. Shocked, guilty, angry, overwhelmed and everything in between. He grinned.',
			'Her mother called her out on ditching her friend and to his friend’s immense shock, even her father admonished her for keeping him waiting. It seemed he had won their approval even before he knew he would want it. They supported him and somehow, they convinced her to spend more time with him. He apologized for being such a “newb”, which made her laugh. There was so much she loved and could talk about that they easily returned to their old ways, only he had a new understanding.',
			'He wanted to kiss his favorite girl. He wanted to hug her and do things with her. When she showed him pornographic anime, he was silent and she must have caught onto his discomfort because after that one time, she never showed him anymore. A few times later, she admitted that she was surprised. She thought boys were obsessed with girls and sex. Even in her clubs and among new friends, raunchy topics were inescapable, though many of the girls were as perverted as the boys and no one was ever harassed, so it was all good, but her friend, a good-looking boy, decent, kind and popular, was so shy. She sat beside him, always a space between them, and asked him what he thought of girls.',
			'He said they were okay, he wasn’t that much interested in other girls.',
			'Are you gay, she wondered.',
			'He didn’t know whether to laugh or cry out. No, he cried. She held out her hands, immediately uttering words to soothe him, but then he said the only girl he liked was her. She froze and he could not bring himself to look at her. He was so scared of her rejection that when she asked if he was playing her, he did not register it at once, but once her tone and words registered to him, he turned to her, saying, No, no. I. The words got caught in his throat and he could see her closing herself to him, not believing him, believing he was bad, believing he was a liar. He felt as if he might cry if she never believed him. He was so overcome by terror that he grabbed the sides of her face and kissed her, his hands and lips shaking.',
			'She pushed against him. She was strong enough to shove him away but maybe part of her hoped he was telling the truth or maybe part of her liked the kiss, whatever it was, he prayed for one chance, for her to understand him. When they parted, he told her he liked her over and over and over again. He was shaking so much that his words were jumbled. He did not stop until he felt her hands on his. Whipping his eyes to hers, he saw that she finally believed him, but he was still so scared. Do you believe me, he whispered.',
			'I don’t know, she said, You mean it?',
			'Retracting his hands, keeping them to himself, his thoughts raced. He was so desperate for her to believe him that he confessed to everything. He told her about the girls he went to for understanding, who then hit on him and how wrong their bodies felt, how disgusted he felt. He told her that she was the girl in his fantasies when he masturbated, that he thought of, dreaming of kissing her, touching her, being naked with her. He told her that he never wanted to be any less closer to her. Since the first day they met, all he ever wanted was to be closer and closer, to hear her talk, to sit beside her, to perhaps hold her hand or rest her head on his shoulder. By the time he finished, he chanced to look up and found a silly happy smile on her face.',
			'She looked up, shaking her head, and laughed to herself. At that moment, he was not so scared. Something about her let him know it was fine and he slumped down. Feeling tired, he still managed to see the opportunity and took it, slumping against her. She did not push him away. She caught him and held him. He was so grateful, then he was thinking and felt guilty because he wanted to know when they could try. Would she kiss him, would they get to sleep together, would she make him wait? He did not dare ask her and the topic was not discussed for months.',
			'Nearly a year passed and they were in eighth grade. Despite his confession the year before, they did not start dating. Her mother even asked him why not and her father laughed at him. When she got home after her club, she grabbed him and dragged him up the stairs to her bedroom, where he noticed a blanket laid out on her floor. She shut the door, pointed at the blanket, telling him to sit as she turned on her computer and navigated to some movies, turning up the volume. He sat on the floor. She got on her hands and knees in front of him. How much do you like me, she asked.',
			'He looked at her computer, listening to the volume of the movie, and then at the blanket she had him sitting on. Looking at her, he wondered, Do you want to do it?',
			'She stared back at him so intensely that he doubted it and tried to think of alternatives until Yes, she said.',
			'He stared back at her. I’d love to.',
			'She smiled and his breath stopped. Are we doing this, he blurted out and instead of answering, she sat up, peeling off her jacket and shirts. He saw her bra, her boobs spilling out of the cups, looked at the curves and folds of her belly. Unable to stop it, he licked his lips. His mouth felt dry and he swallowed thickly. When she looked at him, he looked at her. He tore off his jacket and shirt. Driven by her smile, panting under his breath, he removed his belt, shoved down his pants and looked at her. She fished around the pockets of her jacket and pulled out a condom. Gotta check the size now, she whispered. He would have laughed but he was a little desperate and needed that condom to fit.',
			'After that day, which was awkward, funny and great, they were dating and they were having sex. He was happy. His favorite girl was his dream girl. Life was his.',
			'In high school, he became part of the football team. His favorite girl, his only girl, was a little hesitant about being seen with him or spending time together at school, and in his head, he reminded her that she was the one who had no time for him. As she found, not consciously, she never did have time for him at school. Even after his practice ended, he would wait at her house and chat with her parents. Sometimes, she would be so late as to arrive in the middle of dinner. She usually brushed it off, but then she was thinking about it. Aren’t you too close to my parents, she wondered. He shrugged.',
			'With all his attention on his favorite girl, the relationship with her parents seemed like it just happened. It was there and he would rather never do without it. She asked if that meant she would have to marry him one day. While he had never thought about it, her saying it as if it was something she might not want felt like she was rejecting him, but knowing him enough by then, she grabbed him by the back of his head and rested his head on her boobs, telling him to stop being so insecure.',
			'He loved his girl.',
			'The night he left the party, drawn to the blue light of her bedroom window like a beacon, sitting on her bed and looking at her back, he thought of her body, her curves, her skin, her smell, her warmth. He wanted to hold her, wrap his arms around her. He wanted her on him, riding him. He wanted to feel her weight, the reality of her presence, her curves jiggling, her boobs rising and falling, the sleek of sweat on her skin. He wanted those big beautiful hips filling his hands.',
			'He stopped fantasizing when he felt her hands on his shoulders and her leg beside his. When he looked up, there she was without her glasses, smiling at him. He smiled. “Can I sleep here tonight?”',
			'She scoffed. “I won’t stop you,” she said and settled on his lap, “Not tonight at least.”',
			'He laughed. “Sorry about your homework.”',
			'She shrugged. “Not your fault. You actually insisted on letting me study.” She looked straight at him. “Why do you do that?”',
			'He frowned. “What do you mean?”',
			'She studied him. “Don’t you ever want anything?”',
			'“I want a lot,” he said but she interrupted him, saying “No. More. Don’t you ever want more, more than what you want?”',
			'He shook his head, looking at her, confused what she was asking him. “What you mean?”',
			'She looked at him and sighed. “I mean. What about you? You never ask me to go anywhere with you or to stop and do something for you. It’s.” He watched her, wondering if she had finally become aware of her lack of time for him. She shook her head. “Don’t you want more from me?”',
			'He stared at her. “Not really,” he said tentatively, watching her reaction to him, “I’m not going to ask you to stop doing what you love or being with people who understand things I don’t.” He looked away. “I really don’t ask for much. I just want you to like me.” He glimpsed her stare and added. “And time.”',
			'She stared at him but he did not see. He did not dare to look at her because he knew his words sounded like a loveless child. That could also just be how he thought about it, and maybe he believed it. When her silence stretched on but her weight on him did not move, aware she was staring at him, he chanced a look at her.',
			'“I’m not going to stop liking you even if you make things difficult for me.” He stared at her, surprised. She stared back, deadpan and serious. It reminded him of her father. “And even if I stop liking you,” she said, “I love you.”',
			'He smiled to himself and tried to stop it. His mind went back to earlier and though he could not describe what he was feeling, he muttered, “I want to stay with you tonight.”',
			'“Just stay?” He looked at her. She shifted her weight and smirked. He swallowed and his mouth felt dry. Taking a deep rasping breath, he raised his hands. Aware she was watching, he rested his hands on her hips, feeling the fullness of her sides. She moved forward, settling her weight right on his crotch, and he wrapped his arms around her. His breathing was quick and shallow. She hummed by his ear. “You really like this big girl, don’t you.”',
			'He smiled into her shoulder. “She’s all I want,” he muttered, shifting his hips and pressing into her. She sighed by his ear. Her own breath shuttered as he rolled his hips, rubbing and pressing against her, aware of their pants and underwear between them, which he imagined removing. He imagined seeing her heavy thighs, her wide hips, and the triangle between them that he had seen so many times, yet still he wanted to see it again. Perhaps he would even taste her, listening to her whines and grunts, her heavy breaths, feeling her undulate around him. It made him even harder, so much that it was painful. He might even cum and that didn’t even embarrass him. For the minutes it would take to recover, he could taste her, reach his hands inside and suck her tongue with his.',
			'When she suddenly pulled back, he panicked as her hands took hold of his face and made him look at her. He squeezed his arms around her. She looked at him and chuckled. As confused as he was, she then leaned in with her tongue slipping between his lips and he closed his eyes, relieved. She pressed into him and he lied back, her body covering his as they kissed. She ground into him, making him call out, breathless, “Oh fuck.”',
			'She leaned up, caught his lower lip gently between her teeth, and he shivered, grabbing onto her hips, raising his hips. He felt their clothes becoming wet. He imagined reaching down between them and lowering his fly. He imagined her pushing down her pants and underwear past her knees, spreading her legs at his hips and letting him into her.',
			'“You need a condom?” He hardly heard it, focused on their lips meeting, her tongue against his, their crotches grinding, but when she pulled back and whispered it again. Without thinking, he nodded. He nodded furiously. His eyes shot open when she pressed down on him and locked her legs around his hips, sealing their parts against each other tight. His breath caught in his throat as she leaned over and fished around in the drawer of her nightstand. Her features were dark but part of her nose and lips were found by the blue light.',
			'He heard the crinkle of more than one wrapper grasped in her hand. Holding his breath, he felt like laughing with happiness at the insinuation. His eyes were closed, feeling her grind against him before pulling back, then her hands undid his zipper, lowered his underwear and touched him. She did not yet put the condom on. He heard the rustling of her clothes and when her weight returned to him and her legs were on either side of his, he felt the heat of her skin through his pants. For a moment, he frowned, wishing his pants were gone, then he felt her wetness on his tip. He opened his eyes and looked down. She broke contact. He stared as she put the condom on him.',
			'Not even inch by inch, not by centimeters, it was millimeter by millimeter that she slid the condom down. He stared at her fingers, her hand, the plastic, the rim of the condom lowering. If she laughed, it was a distant and indistinct sound but knowing her, she found his intense concentration, her hand’s silhouette surrounded by blue light, funny. He did not see it as the rim and her fingers met the hair of his crotch, and couldn’t process, feeling her slide down on him.',
			'For some reason, he saw her parents in his head then and remembered her asking if she would have to marry him one day. He opened his eyes and looked at her. She peered down at him and despite being cast in shadow, he saw all her beautiful features, her round cheeks, her messy hair, even the dent on the bridge of her nose left by her glasses. He grasped her hips and ground up into her. He didn’t care about tomorrow or if their relationship would last past high school and college.',
			'Rearing up, he sat up and wrapped his arms around her, holding her tight, pressing as much of himself against her as he could and held onto her, immersing himself in her wetness, her weight, her smell, her warmth, and saw her in his head, the hours she spent showing him how to play the DS and playing back to back in her room, the hours she talked on and on about Rick and Morty, hoping for tickets to see Meghan Trainer or Hairspray, the perverted antics of the white anime club members and the quirky Asian kids, the hours she spent making costumes and making her models, the hours spent with her parents waiting for her or eating dinner with her, and he knew if he could have this feeling, the feeling of her on him and around him, that she was in his hands, in his arms and connected to him, he’d have all he needed.',
			'This was home.'
		]
	},
	{
		title: "Not a Question",
		text: [
			'“I wasn’t asking.”',
			'Paula stopped, surprised, and peered at Mark. “What you mean—you did ask.”',
			'Mark glared back at her. “No, it was a statement. I didn’t ask.”',
			'“Then don’t say it like a question!”',
			'Mark jerked back. “A person can say something like a question without it being a question—hell, you did it when you said ‘So is that how it goes.’ Was that a question?”',
			'“No.”',
			'“Did I interpret that wrong?”',
			'“No.”',
			'“Cause it sure didn’t sound like a—”',
			'“No!” Paula and Mark glared at each other, the former frustrated and the other simply angry. But before Paula could say anything, Mark interrupted.',
			'“My statement was a statement. You better than anyone should remember why.”',
			'“No, I don’t. Why?”',
			'“Cause my dad died from the same fucking surgery!” Only then did Paula remember and she paled, remembering. It was so long ago, so far into their past, how was she supposed to remember, but as that thought occurred to her, she slapped her own ego because she knew, she did remember that it wasn’t that one devastating event. She had been there and witnessed its ripple effect for years breaking his mom with debt, his brothers with grief and chaos, and he ran to her to help him laugh again. How could she forget? But she did.',
			'With a shake of his head, Mark turned from her and picked up his bag. He pushed back, saying, “I gotta go. I’m not in the right headspace right now.”',
			'She grabbed for his arm and cried, “I’m sorry,” even if it disturbed the rest of the café. “I’m sorry.”',
			'Mark looked at her. He didn’t look angry, just sad. “Yeah. I know. But not right now. Let me.” He turned from her. “Let me get over it first.”',
			'Her hands fell away and she watched him go. She felt like crying, she felt the stares, but it did not feel as if she were the right one to cry. Sitting back, she looked over the table, over their coffee cups, his pastry, the crumbs, and in her head, there was so much that it was nothing. If someone asked, she could not expound to them all that she was thinking or feeling or remembering or imagining. She reached behind her, grabbed her bag from the chair and stood, heading out the way Mark had gone, but while he went left, she would go right.'
		]
	}
]

// command: 1-w:p r - = Replace every first word of paragraph with '-'

const command = (ipt) => {
	const tokens = ipt.split(' ')
}

const word = (text) => text.split(/[ .?!:;,'"\n]/)

const sentence = (text) => text.split(/\n+/).map(p => p.split(/[?!.]+/))

const paragraph = (text) => text.split(/\n+/)

const analyzer = {
	wrd:
}

export default { texts, analyzer }


'
